### Obtener todos los clientes

GET http://localhost:3000/api/clientes

### Obtener un cliente por dni

GET http://localhost:3000/api/clientes/2058365

### Crear un cliente

POST http://localhost:3000/api/clientes/
Content-Type: application/json

{
    "dni": "124212",
    "nombre": "Juan",
    "apellido": "Perez",
    "email": "juan@gmail.com",
    "fechaNacimiento": "1990-01-01"
}

### modificar un cliente (PUT - recurso completo)

PUT http://localhost:3000/api/clientes/2058365
Content-Type: application/json

{
    "dni": "1234567",
    "nombre": "Carlos",
    "apellido": "Perez",
    "email": "carlos@gmail.com",
    "fechaNacimiento": "1995-01-01"
}

### modificar un cliente (PATCH - recurso parcial)

PATCH http://localhost:3000/api/clientes/12345678
Content-Type: application/json

{
    "email": "mailcambiado@gmail.com",
    "fechaNacimiento": "1995-05-10"
}

### Borrar un cliente

DELETE http://localhost:3000/api/clientes/12345678